// <auto-generated />
using System;
using EventRegistration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventRegistration.Migrations
{
    [DbContext(typeof(EventRegistrationContext))]
    partial class EventRegistrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventRegistration.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "C",
                            EndDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "資訊系迎新茶會",
                            EventType = 0,
                            IsActive = true,
                            MaxParticipants = 100,
                            StartDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "校園路跑活動",
                            EventType = 1,
                            IsActive = true,
                            MaxParticipants = 200,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Department = "B",
                            EndDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "企管系職涯講座",
                            EventType = 0,
                            IsActive = true,
                            MaxParticipants = 80,
                            StartDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EventRegistration.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EventRegistration.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "admin",
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@school.edu.tw",
                            Name = "系統管理員",
                            Password = "admin123",
                            Remarks = "系統預設管理員帳號",
                            Role = 3
                        },
                        new
                        {
                            Id = 2,
                            Account = "T001",
                            CreatedAt = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "C",
                            Email = "wang@school.edu.tw",
                            Name = "王大明",
                            Password = "teacher123",
                            Phone = "0912345601",
                            Remarks = "資訊工程系教授",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Account = "T002",
                            CreatedAt = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "B",
                            Email = "lee@school.edu.tw",
                            Name = "李小華",
                            Password = "teacher123",
                            Phone = "0912345602",
                            Remarks = "企業管理系副教授",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Account = "C11200001",
                            CreatedAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "C",
                            Email = "c11200001@student.school.edu.tw",
                            EnrollmentYear = 112,
                            Name = "陳曉明",
                            Password = "student123",
                            Phone = "0912345611",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            Account = "C11200015",
                            CreatedAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "C",
                            Email = "c11200015@student.school.edu.tw",
                            EnrollmentYear = 112,
                            Name = "林佳穎",
                            Password = "student123",
                            Phone = "0912345612",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            Account = "F11200022",
                            CreatedAt = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "F",
                            Email = "f11200022@student.school.edu.tw",
                            EnrollmentYear = 112,
                            Name = "張雅婷",
                            Password = "student123",
                            Phone = "0912345613",
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            Account = "B11100008",
                            CreatedAt = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "B",
                            Email = "b11100008@student.school.edu.tw",
                            EnrollmentYear = 111,
                            Name = "劉志強",
                            Password = "student123",
                            Phone = "0912345614",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            Account = "M11310003",
                            CreatedAt = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "M",
                            Email = "m11310003@student.school.edu.tw",
                            EnrollmentYear = 113,
                            Name = "黃建國",
                            Password = "student123",
                            Phone = "0912345615",
                            Remarks = "碩士班研究生",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            Account = "E11101010",
                            CreatedAt = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "E",
                            Email = "e11101010@student.school.edu.tw",
                            EnrollmentYear = 111,
                            Name = "吳明輝",
                            Password = "student123",
                            Phone = "0912345616",
                            Remarks = "進修部學生",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Account = "C10900025",
                            CreatedAt = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "C",
                            Email = "chou.alumni@gmail.com",
                            EnrollmentYear = 109,
                            Name = "周佩君",
                            Password = "alumni123",
                            Phone = "0912345617",
                            Remarks = "2024年畢業校友",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            Account = "B10800012",
                            CreatedAt = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "B",
                            Email = "cheng.alumni@gmail.com",
                            EnrollmentYear = 108,
                            Name = "鄭家豪",
                            Password = "alumni123",
                            Phone = "0912345618",
                            Remarks = "2023年畢業校友，現任職科技業",
                            Role = 1
                        });
                });

            modelBuilder.Entity("EventRegistration.Models.Registration", b =>
                {
                    b.HasOne("EventRegistration.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventRegistration.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventRegistration.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EventRegistration.Models.User", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
